name: Verification Security and Build

on: push

jobs:
  verification-securite:
    runs-on: ubuntu-latest
    steps:
      - name: Importer le projet
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Build Docker image
        run: |
          docker build -t devsecure-api .
          docker run -p 3000:3000 devsecure-api &

      - name: Trivy (Scan des vulnérabilités dans l'image Docker)
        uses: aquasecurity/trivy-action@master
        with:
            image-ref: devsecure-api
            format: table
            vuln-type: 'os,library'
            severity: 'CRITICAL,HIGH'

      - name: Snyk (Analyse des dépendances Python et du container)
        uses: snyk/actions/python@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          args: --severity-threshold=high
